import {
  integer,
  text,
  sqliteTable,
  index,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// ============================================================================
// AOR SERVICES & WORKER PORTAL
// ============================================================================

export const contractors = sqliteTable(
  "contractors",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contractorCode: text("contractorCode", { length: 20 }).unique(), // Auto-generated: CTR-0001
    customerId: integer("customerId").notNull(),
    // Personal info
    firstName: text("firstName", { length: 100 }).notNull(),
    lastName: text("lastName", { length: 100 }).notNull(),
    email: text("email", { length: 320 }).notNull(),
    phone: text("phone", { length: 20 }),
    dateOfBirth: text("dateOfBirth"),
    nationality: text("nationality", { length: 100 }),
    idNumber: text("idNumber", { length: 100 }),
    idType: text("idType", { length: 50 }),
    // Address
    address: text("address"),
    city: text("city", { length: 100 }),
    state: text("state", { length: 100 }),
    country: text("country", { length: 100 }).notNull(), // Service country
    postalCode: text("postalCode", { length: 20 }),
    // Service details
    jobTitle: text("jobTitle", { length: 255 }).notNull(),
    jobDescription: text("jobDescription"),
    department: text("department", { length: 100 }),
    startDate: text("startDate").notNull(),
    endDate: text("endDate"),
    status: text("status", { enum: [
      "pending_review",
      "active",
      "terminated",
    ] }).default("pending_review").notNull(),
    
    // Financial Config
    currency: text("currency", { length: 3 }).default("USD").notNull(),
    paymentFrequency: text("paymentFrequency", { enum: [
      "monthly",
      "semi_monthly",
      "milestone",
    ] }).default("monthly").notNull(),
    
    // Payment Rates (Flexible based on frequency)
    rateType: text("rateType", { enum: ["fixed_monthly", "hourly", "milestone_only"] }).default("fixed_monthly").notNull(),
    rateAmount: text("rateAmount"), // e.g. Monthly Salary or Hourly Rate
    
    // Bank Details (Encrypted/JSON in real app, but text here for simplicity as per existing patterns)
    bankDetails: text("bankDetails", { mode: "json" }),
    
    // Metadata
    notes: text("notes"),
    defaultApproverId: integer("defaultApproverId"), // Admin user ID for approvals
    createdAt: integer("createdAt", { mode: "timestamp" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    ctrCustomerIdIdx: index("ctr_customer_id_idx").on(table.customerId),
    ctrEmailIdx: index("ctr_email_idx").on(table.email),
    ctrStatusIdx: index("ctr_status_idx").on(table.status),
    ctrCountryIdx: index("ctr_country_idx").on(table.country),
  })
);

export type Contractor = typeof contractors.$inferSelect;
export type InsertContractor = typeof contractors.$inferInsert;

// ── Contractor Invoices (Generated by system or submitted by contractor) ──
export const contractorInvoices = sqliteTable(
  "contractor_invoices",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    invoiceNumber: text("invoiceNumber", { length: 100 }).unique(), // CTR-INV-2024001
    contractorId: integer("contractorId").notNull(),
    customerId: integer("customerId").notNull(),
    
    invoiceDate: text("invoiceDate").notNull(),
    dueDate: text("dueDate"),
    periodStart: text("periodStart"),
    periodEnd: text("periodEnd"),
    
    currency: text("currency", { length: 3 }).notNull(),
    totalAmount: text("totalAmount").notNull(),
    
    status: text("status", { enum: [
      "draft",
      "pending_approval",
      "approved",
      "paid",
      "rejected",
    ] }).default("draft").notNull(),
    
    // Linking to core finance
    clientInvoiceId: integer("clientInvoiceId"), // If billed to client in a bundle
    
    approvedBy: integer("approvedBy"),
    approvedAt: integer("approvedAt", { mode: "timestamp" }),
    rejectedReason: text("rejectedReason"),
    
    createdAt: integer("createdAt", { mode: "timestamp" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    ciContractorIdIdx: index("ci_contractor_id_idx").on(table.contractorId),
    ciCustomerIdIdx: index("ci_customer_id_idx").on(table.customerId),
    ciStatusIdx: index("ci_status_idx").on(table.status),
  })
);

export type ContractorInvoice = typeof contractorInvoices.$inferSelect;
export type InsertContractorInvoice = typeof contractorInvoices.$inferInsert;

export const contractorInvoiceItems = sqliteTable(
  "contractor_invoice_items",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    invoiceId: integer("invoiceId").notNull(),
    description: text("description").notNull(),
    quantity: text("quantity").default("1").notNull(),
    unitPrice: text("unitPrice").notNull(),
    amount: text("amount").notNull(),
    itemType: text("itemType", { enum: [
      "service_fee",
      "hourly_work",
      "milestone",
      "expense",
      "adjustment",
    ] }).notNull(),
    
    // Links
    milestoneId: integer("milestoneId"),
    adjustmentId: integer("adjustmentId"),
    
    createdAt: integer("createdAt", { mode: "timestamp" }).defaultNow().notNull(),
  },
  (table) => ({
    ciiInvoiceIdIdx: index("cii_invoice_id_idx").on(table.invoiceId),
  })
);

export type ContractorInvoiceItem = typeof contractorInvoiceItems.$inferSelect;
export type InsertContractorInvoiceItem = typeof contractorInvoiceItems.$inferInsert;

// ── Milestones ──
// Status workflow aligned with EOR adjustments/leave, with extra "pending" state:
// pending (client creates, waiting for worker) → submitted (worker submits) →
// client_approved/client_rejected → admin_approved/admin_rejected → locked
export const contractorMilestones = sqliteTable(
  "contractor_milestones",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contractorId: integer("contractorId").notNull(),
    customerId: integer("customerId").notNull(), // Auto-filled from contractor
    title: text("title", { length: 255 }).notNull(),
    description: text("description"),
    amount: text("amount").notNull(),
    currency: text("currency", { length: 3 }).notNull(),
    
    // Status workflow: pending → submitted → client_approved/client_rejected → admin_approved/admin_rejected → locked
    status: text("status", { enum: [
      "pending",
      "submitted",
      "client_approved",
      "client_rejected",
      "admin_approved",
      "admin_rejected",
      "locked",
    ] }).default("pending").notNull(),
    
    dueDate: text("dueDate"),
    completedAt: integer("completedAt", { mode: "timestamp_ms" }),
    
    // Deliverable files uploaded by worker when submitting
    deliverableFileUrl: text("deliverableFileUrl"),
    deliverableFileKey: text("deliverableFileKey", { length: 500 }),
    deliverableFileName: text("deliverableFileName", { length: 255 }),
    submissionNote: text("submissionNote"), // Worker's note when submitting the milestone
    
    // Approval tracking (aligned with EOR adjustments)
    submittedBy: integer("submittedBy"), // Worker user ID who submitted
    clientApprovedBy: integer("clientApprovedBy"), // Portal contact ID
    clientApprovedAt: integer("clientApprovedAt", { mode: "timestamp_ms" }),
    clientRejectionReason: text("clientRejectionReason"),
    adminApprovedBy: integer("adminApprovedBy"), // Admin user ID
    adminApprovedAt: integer("adminApprovedAt", { mode: "timestamp_ms" }),
    adminRejectionReason: text("adminRejectionReason"),
    
    // Target month
    effectiveMonth: text("effectiveMonth"), // Which month this applies to (YYYY-MM-01), set when submitted
    
    // Link to contractor invoice when locked
    invoiceId: integer("invoiceId"), // Linked to contractorInvoice when included
    
    createdAt: integer("createdAt", { mode: "timestamp_ms" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    cmContractorIdIdx: index("cm_contractor_id_idx").on(table.contractorId),
    cmCustomerIdIdx: index("cm_customer_id_idx").on(table.customerId),
    cmStatusIdx: index("cm_status_idx").on(table.status),
    cmEffectiveMonthIdx: index("cm_effective_month_idx").on(table.effectiveMonth),
  })
);

export type ContractorMilestone = typeof contractorMilestones.$inferSelect;
export type InsertContractorMilestone = typeof contractorMilestones.$inferInsert;

// ── Adjustments (Bonuses, Expenses) ──
// Status workflow aligned with EOR adjustments:
// submitted → client_approved/client_rejected → admin_approved/admin_rejected → locked
export const contractorAdjustments = sqliteTable(
  "contractor_adjustments",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contractorId: integer("contractorId").notNull(),
    customerId: integer("customerId").notNull(), // Auto-filled from contractor
    type: text("type", { enum: ["bonus", "expense", "deduction"] }).notNull(),
    description: text("description").notNull(),
    amount: text("amount").notNull(),
    currency: text("currency", { length: 3 }).notNull(),
    
    // Receipt/attachment
    attachmentUrl: text("attachmentUrl"),
    attachmentFileKey: text("attachmentFileKey", { length: 500 }),
    
    // Status workflow: submitted → client_approved/client_rejected → admin_approved/admin_rejected → locked
    status: text("status", { enum: [
      "submitted",
      "client_approved",
      "client_rejected",
      "admin_approved",
      "admin_rejected",
      "locked",
    ] }).default("submitted").notNull(),
    submittedBy: integer("submittedBy"), // User ID who created this
    
    // Approval tracking
    clientApprovedBy: integer("clientApprovedBy"), // Portal contact ID who approved/rejected
    clientApprovedAt: integer("clientApprovedAt", { mode: "timestamp_ms" }),
    clientRejectionReason: text("clientRejectionReason"),
    adminApprovedBy: integer("adminApprovedBy"), // Admin user ID who confirmed
    adminApprovedAt: integer("adminApprovedAt", { mode: "timestamp_ms" }),
    adminRejectionReason: text("adminRejectionReason"),
    
    // Target month
    effectiveMonth: text("effectiveMonth").notNull(), // Which month this applies to (YYYY-MM-01)
    
    // Link to contractor invoice when locked
    invoiceId: integer("invoiceId"), // Linked to contractorInvoice when included
    
    createdAt: integer("createdAt", { mode: "timestamp_ms" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    caContractorIdIdx: index("ca_contractor_id_idx").on(table.contractorId),
    caCustomerIdIdx: index("ca_customer_id_idx").on(table.customerId),
    caStatusIdx: index("ca_status_idx").on(table.status),
    caEffectiveMonthIdx: index("ca_effective_month_idx").on(table.effectiveMonth),
  })
);

export type ContractorAdjustment = typeof contractorAdjustments.$inferSelect;
export type InsertContractorAdjustment = typeof contractorAdjustments.$inferInsert;

// ── Contractor Documents (aligned with employee_documents) ──
// For storing contractor agreements, ID copies, tax forms, etc.
// TODO: Add admin/client portal UI to manage these documents
export const contractorDocuments = sqliteTable(
  "contractor_documents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contractorId: integer("contractorId").notNull(),
    documentType: text("documentType", { enum: [
      "agreement",        // Contractor agreement / SOW
      "nda",              // Non-disclosure agreement
      "passport",
      "national_id",
      "tax_form",         // W-9, W-8BEN, etc.
      "insurance",        // Liability insurance
      "certification",    // Professional certifications
      "other",
    ] }).notNull(),
    documentName: text("documentName", { length: 255 }).notNull(),
    fileUrl: text("fileUrl").notNull(),
    fileKey: text("fileKey", { length: 500 }).notNull(),
    mimeType: text("mimeType", { length: 100 }),
    fileSize: integer("fileSize"),
    notes: text("notes"),
    uploadedAt: integer("uploadedAt", { mode: "timestamp_ms" }).defaultNow().notNull(),
    createdAt: integer("createdAt", { mode: "timestamp_ms" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    cdContractorIdIdx: index("cd_contractor_id_idx").on(table.contractorId),
    cdDocTypeIdx: index("cd_doc_type_idx").on(table.documentType),
  })
);

export type ContractorDocument = typeof contractorDocuments.$inferSelect;
export type InsertContractorDocument = typeof contractorDocuments.$inferInsert;

// ── Contractor Contracts (aligned with employee_contracts) ──
// For storing signed contractor agreements with effective dates
// TODO: Add admin/client portal UI to manage these contracts
export const contractorContracts = sqliteTable(
  "contractor_contracts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contractorId: integer("contractorId").notNull(),
    contractType: text("contractType", { length: 100 }), // e.g. "Service Agreement", "SOW", "Amendment"
    fileUrl: text("fileUrl"),
    fileKey: text("fileKey", { length: 500 }),
    signedDate: text("signedDate"),
    effectiveDate: text("effectiveDate"),
    expiryDate: text("expiryDate"),
    status: text("status", { enum: ["draft", "signed", "expired", "terminated"] }).default("draft").notNull(),
    createdAt: integer("createdAt", { mode: "timestamp_ms" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    ccContractorIdIdx: index("cc_contractor_id_idx").on(table.contractorId),
    ccStatusIdx: index("cc_status_idx").on(table.status),
  })
);

export type ContractorContract = typeof contractorContracts.$inferSelect;
export type InsertContractorContract = typeof contractorContracts.$inferInsert;

// ── Employee Payslips ──
// Admin uploads payslip PDF files for employees to view in Worker Portal.
// This is separate from payroll_runs/payroll_items which are internal accounting records.
// TODO: Add admin portal UI to upload payslips
export const employeePayslips = sqliteTable(
  "employee_payslips",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    employeeId: integer("employeeId").notNull(),
    customerId: integer("customerId").notNull(), // Auto-filled from employee
    // Period
    payPeriod: text("payPeriod").notNull(), // YYYY-MM format, e.g. "2026-03"
    payDate: text("payDate"), // Actual pay date, e.g. "2026-03-25"
    // File
    fileUrl: text("fileUrl").notNull(),
    fileKey: text("fileKey", { length: 500 }).notNull(),
    fileName: text("fileName", { length: 255 }).notNull(),
    mimeType: text("mimeType", { length: 100 }).default("application/pdf"),
    fileSize: integer("fileSize"),
    // Metadata
    currency: text("currency", { length: 3 }),
    grossAmount: text("grossAmount"), // Optional summary for display
    netAmount: text("netAmount"),     // Optional summary for display
    notes: text("notes"),
    // Publishing control: only published payslips are visible to workers
    isPublished: integer("isPublished", { mode: "boolean" }).default(false).notNull(),
    publishedAt: integer("publishedAt", { mode: "timestamp_ms" }),
    uploadedBy: integer("uploadedBy"), // Admin user ID who uploaded
    createdAt: integer("createdAt", { mode: "timestamp_ms" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    epEmployeeIdIdx: index("ep_employee_id_idx").on(table.employeeId),
    epCustomerIdIdx: index("ep_customer_id_idx").on(table.customerId),
    epPayPeriodIdx: index("ep_pay_period_idx").on(table.payPeriod),
    epPublishedIdx: index("ep_published_idx").on(table.isPublished),
    epEmployeePeriodIdx: uniqueIndex("ep_employee_period_idx").on(table.employeeId, table.payPeriod),
  })
);

export type EmployeePayslip = typeof employeePayslips.$inferSelect;
export type InsertEmployeePayslip = typeof employeePayslips.$inferInsert;

// ── Worker Portal Auth ──
// Unified authentication for both Employee (EOR) and Contractor (AOR) users.
// Each worker_user links to either an employee OR a contractor (mutually exclusive).
export const workerUsers = sqliteTable(
  "worker_users",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    email: text("email", { length: 320 }).unique().notNull(),
    passwordHash: text("passwordHash", { length: 255 }),
    contractorId: integer("contractorId").unique(), // 1:1 link to contractor profile (AOR)
    employeeId: integer("employeeId").unique(),     // 1:1 link to employee profile (EOR)
    
    // Worker type derived from which ID is set: "contractor" if contractorId, "employee" if employeeId
    
    isActive: integer("isActive", { mode: "boolean" }).default(true).notNull(),
    isEmailVerified: integer("isEmailVerified", { mode: "boolean" }).default(false).notNull(),
    
    inviteToken: text("inviteToken", { length: 255 }),
    inviteExpiresAt: integer("inviteExpiresAt", { mode: "timestamp" }),
    resetToken: text("resetToken", { length: 255 }),
    resetExpiresAt: integer("resetExpiresAt", { mode: "timestamp" }),
    
    lastLoginAt: integer("lastLoginAt", { mode: "timestamp" }),
    createdAt: integer("createdAt", { mode: "timestamp" }).defaultNow().notNull(),
    updatedAt: integer("updatedAt", { mode: "timestamp" }).defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => ({
    wuEmailIdx: uniqueIndex("wu_email_idx").on(table.email),
    wuContractorIdIdx: uniqueIndex("wu_contractor_id_idx").on(table.contractorId),
    wuEmployeeIdIdx: uniqueIndex("wu_employee_id_idx").on(table.employeeId),
  })
);

export type WorkerUser = typeof workerUsers.$inferSelect;
export type InsertWorkerUser = typeof workerUsers.$inferInsert;

// ── Migration Mapping ──
export const migrationIdMap = sqliteTable(
  "migration_id_map",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    entityType: text("entityType", { enum: ["employee_to_contractor", "user_to_worker_user"] }).notNull(),
    oldId: integer("oldId").notNull(),
    newId: integer("newId").notNull(),
    migratedAt: integer("migratedAt", { mode: "timestamp" }).defaultNow().notNull(),
  },
  (table) => ({
    mimOldIdIdx: index("mim_old_id_idx").on(table.oldId),
    mimNewIdIdx: index("mim_new_id_idx").on(table.newId),
    mimUniqueIdx: uniqueIndex("mim_unique_idx").on(table.entityType, table.oldId),
  })
);

export type MigrationIdMap = typeof migrationIdMap.$inferSelect;
export type InsertMigrationIdMap = typeof migrationIdMap.$inferInsert;
